### ISSUE TITLE
macでフォントが取得できない

### ISSUE THREAD

**Issue by HidemaruOwO** [Comamoca/stampy#3]
インストールしたので、試しに実行してみるとフォントが取得できないというエラーが発生しました
<img width="794" alt="image" src="https://user-images.githubusercontent.com/82384920/187125954-ae1be75d-39bd-4e6e-9aee-b2e16297a0f6.png">

**Comment by Comamoca** [comment]
issueありがとうございます。🙇
実行時の背景がよく見えないので、

- Pythonのバージョン
- stampyをインストールした方法
- 実行手順の詳細

以上の事柄を教えて下さい。

**Comment by HidemaruOwO** [comment]
求められたものは以下の通りです

## Pythonバージョン
```bash
$ python3 --version                                                                                                                                                                                          
Python 3.10.6
```
## インストール方法
```bash
$ pip3 install stampy
```
## 実行
```bash
$ stampy おはよう
Traceback (most recent call last):
  File "/opt/homebrew/bin/stampy", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/stampy/main.py", line 84, in main
    font = ImageFont.truetype(font_path, font_size)
  File "/opt/homebrew/lib/python3.10/site-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/opt/homebrew/lib/python3.10/site-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/opt/homebrew/lib/python3.10/site-packages/PIL/ImageFont.py", line 247, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by Comamoca** [comment]
ありがとうございます。
[こちら](https://github.com/Comamoca/stampy/commit/81b63d1273c68d00ff797aeec7d1ed992fed6379)のcommitで修正をしたので確認してみてください。
